teamforage/forage-ios-sdk

Sample/SampleForageSDK/Foundation/Network/SampleAPI.swift
Sources/ForageSDK/Foundation/Network/ForageAPI.swift
Sources/ForageSDK/Foundation/Network/ForageService.swift
Sources/ForageSDK/Foundation/Network/Model/MessageResponse.swift

Ticket: [SYM-81](https://linear.app/joinforage/issue/SYM-81/[ios]-polling-on-capture-payment)
*This PR needs to be merged after [SYM-74](https://github.com/teamforage/forage-ios-sdk/pull/13)*
Sub-tickets:

[SYM-81] Polling for capture payment

---

Sample/SampleForageSDK/AppDelegate.swift
Sample/SampleForageSDK/Base.lproj/Main.storyboard
Sample/SampleForageSDK/Foundation/Network/SampleAPI.swift
Sources/ForageSDK/Component/ForagePANTextField/ForagePANTextField.swift
Sources/ForageSDK/ForageSDK.swift

The card input field validation was very strict and wouldn't allow non-production EBT cards to be entered.
Although this is the ideal functionality in practice, we need to allow our Merchants to pass in specific EBT cards to complete failure scenarios.
Tested this change locally in the sample app.

Adjust validation to allow invalid cards to be sent through iframe

---

README.md
Sample/SampleForageSDK/Foundation/Base/ClientSharedData.swift
Sample/SampleForageSDK/Foundation/Network/Model/Address.swift
Sample/SampleForageSDK/Foundation/Network/Model/CreatePaymentRequest.swift
Sample/SampleForageSDK/Foundation/Network/Model/ForageBalanceModel.swift
Sample/SampleForageSDK/Foundation/Network/Model/ForageCaptureModel.swift
Sample/SampleForageSDK/Foundation/Network/Model/ForagePANModel.swift
Sample/SampleForageSDK/Foundation/Network/SampleAPI.swift
Sample/SampleForageSDK/Sections/CardNumber/CardNumberView.swift
Sample/SampleForageSDK/Sections/CreatePayment/CreatePaymentView.swift
Sources/ForageSDK/Foundation/ForageSDK+ForageServices.swift
Sources/ForageSDK/Foundation/Network/ForageAPI.swift
Sources/ForageSDK/Foundation/Network/Model/ForagePANRequestModel.swift
Sources/ForageSDK/Foundation/Network/Model/PaymentMethodModel.swift
Tests/ForageSDKTests/ForageServiceTests.swift
Tests/ForageSDKTests/Mock/ForageMocks.swift

- add ~optional~ **required** `userID` param to `tokenizeEBTCard`
- Update sample app to display `userID`
- Update `README.md` to include new `userID` param
- Attach `userID` in `createPayment()` calls in the sample app
We (Andres + Kimberlee and I) made userID required because of the complexity + time cost involved with making it optional.
To ensure the dev experience remains pleasant and to simplify sandboxing / trialing the SDK – we make the README snippet value for `userID = UUID.init().uuidString`.
- Payments API v2023-03-31 needs to be released in order to reliably test my changes end-to-end.
Verified that as a consumer of the Android SDK, userId is truly optional
---
**Depends on Payments API v 2023-03-31 being released**
**:warning: This PR can only be released once pr #38 is …

[FOR-1842] Add support for userID param on `tokenizeEBTCard`

---

Sample/SampleForageSDK/Foundation/Network/SampleAPI.swift
Sources/ForageSDK/Component/ForagePINTextField/ForagePINTextField.swift
Sources/ForageSDK/Foundation/ForageSDK+ForageServices.swift
Sources/ForageSDK/Foundation/Network/ForageAPI.swift

When a user submits for balance or capture, we send the PIN to VGS and then clear the text field.
The FNS requires that this feature be baked in to each PIN submit.
I tested locally with an emulator.

[FX-57] Clear PIN when a user submits balance or capture

---

Sample/SampleForageSDK/Sections/CapturePayment/CapturePaymentView.swift
Sample/SampleForageSDK/Sections/CapturePayment/CapturePaymentViewController.swift
Sample/SampleForageSDK/Sections/RequestBalance/RequestBalanceView.swift
Sample/SampleForageSDK/Sections/RequestBalance/RequestBalanceViewController.swift
Sources/ForageSDK/Component/ForagePINTextField/ForagePINTextField.swift
Sources/ForageSDK/Component/ForagePINTextField/Protocol/BtPINTextField.swift
Sources/ForageSDK/Component/ForagePINTextField/Protocol/VaultTextFieldDelegate.swift
Sources/ForageSDK/Component/ForagePINTextField/Protocol/VaultWrapper.swift
Sources/ForageSDK/Component/ForagePINTextField/Protocol/VgsPINTextField.swift
Sources/ForageSDK/Component/ForagePINTextField/Vault/BtPINTextField.swift
Sources/ForageSDK/Component/ForagePINTextField/Vault/VgsPINTextField.swift
Sources/ForageSDK/Foundation/Protocol/ForageElement.swift
Sources/ForageSDK/Foundation/Protocol/ForageElementDelegate.swift
Tests/ForageSDKTests/ForagePINTextFieldTests.swift

Expose three fields/functions for the PIN element:
- `becomeFirstResponder()`
- `resignFirstResponder()`
- `isFirstResponder`
Update the sample app to make use of the `becomeFirstResponder()` method, which will be checked in the qa-test repo.
This PR also does a lot of general cleanup to remove exposed functions that should never have been exposed. Besides the visual changes an external dev wants to apply to the input fields, there are very few functions that they should be able to edit on each field.
I adjusted the internal interface to comply with the pattern that Devin mentioned for building up interfaces. This internal interface will change to fit our needs going forward, but is a clean way to understand what each vault should be able to support under the hood for the PIN field to …

[FX-369] Expose focus function and isFocused flag

---

README.md
Sample/SampleForageSDK/Sections/CardNumber/CardNumberView.swift
Sample/SampleForageSDK/Sections/CardNumber/CardNumberViewController.swift
Sources/ForageSDK/Component/ForagePANTextField/ForagePANTextField.swift
Sources/ForageSDK/Foundation/ForageSDK+ForageServices.swift
Tests/ForageSDKTests/ForagePANTextFieldTests.swift
Tests/ForageSDKTests/ForagePINTextFieldTests.swift

Have the PAN element implement `ForageElement` and wire up the `onFocusChange` and `onTextChange` events.
Added unit tests to check new implementation and adjust qa-tests to check for the updated state values that are displayed in the sample app.
https://github.com/teamforage/forage-ios-sdk/assets/89605898/3808cc29-40d2-45c3-8199-cfa3ef3d5d48

[FX-387] Implement onFocusChange and onTextChange for PAN

---

ForageSDK.podspec
Package.swift

Lower the minimum iOS version from 14 to 13 so we don't break GoPuff.
Unit tests and qa-tests pass locally.

[FX-400] Lower minimum iOS version to 13

---

Tests/ForageSDKTests/ForageServiceTests.swift
Tests/ForageSDKTests/Mock/ForageMocks.swift

- Use expectations to properly test the `LiveForageService`
- Add `bt_alias` to fix get X-KEY test
- Skip tests that need TLC before they can be tested.
Skipped polling-related tests since it's very difficult to mock/stub the underlying polling methods as the polling methods are in `extension`s
I also tried using the [MockingBird](https://mockingbirdswift.com/) library to combat this issue^ and its limitation is that extensions cannot be mocked or stubbed using the framework
So ultimately, we need to refactor our polling logic to be easier to test – and we should also add atomic unit tests for the polling methods.

[FX-391] Fix ForageService tests

---

README.md
Sample/SampleForageSDK/Foundation/Base/ClientSharedData.swift
Sample/SampleForageSDK/Sections/CardNumber/CardNumberView.swift
Sources/ForageSDK/Foundation/ForageSDK+ForageServices.swift
Sources/ForageSDK/Foundation/Network/ForageAPI.swift
Sources/ForageSDK/Foundation/Network/Model/ForagePANRequestModel.swift
Sources/ForageSDK/Foundation/Network/Model/PaymentMethodModel.swift
Sources/ForageSDK/Foundation/Network/Provider.swift
Tests/ForageSDKTests/ForageServiceTests.swift
Tests/ForageSDKTests/Mock/ForageMocks.swift

- Add optional reusable param to README
- Add/display reusable value to Card Number View
@devinmorgan  I considered moving [individual params (reusable, customerID, merchantAccount) to an object](https://linear.app/joinforage/issue/FX-363/android-move-reusable-and-customerid-args-into-optionsconfig) – but the position of the params will still matter even if we separate the params into a separate struct
- Test when reusable is missing from the call to `tokenizeEBTCard`, `reusable` is true ✅ 
- Test when reusable is true, is `reusable` true in the response (in the Card Number View) ✅ 
- Test when reusable is false, is `reusable` false... ✅ 
Can be released as-is. This is a minor-level version change since the reusable flag is …

[FX-269] Add support for optional reusable param

---

.gitignore
.slather.yml

Minor quality of life improvements.
- Add `.DS_Store` to `.gitignore`
- Add additional `Library` paths 
We want to make sure to ignore `Library` locally when generating coverage reports even if it's on a slightly different relative path. Within GitHub, it's 3 layers above the project dir. My local machine is 2, and it's possible some devs have 1 if they're cloning their project straight to their home. 
I noticed `.DS_Store` files were being staged while I was updating this, so I added it to `.gitignore`.

[POP-92] Code coverage fixups

---

Sources/ForageSDK/Component/ForagePINTextField/ForagePINTextField.swift
Sources/ForageSDK/Foundation/ForageSDK+ForageServices.swift
Tests/ForageSDKTests/ForagePINTextFieldTests.swift

- Add internal `PINTextFeild.enable` and `PINTextFeild.disable` methods 
- Clear text after polling response is received or if there's another failure (e.g. getting encryption key)
- Disable PIN text field on submit (visually + functionally) 
- Enable PIN text field after submission is complete
Screen recording: https://joinforage.slack.com/archives/C031SJGSZV0/p1692230961730419
https://linear.app/joinforage/issue/FX-426/clear-pin-text-on-submit-in-ios-sdk
Added unit tests

[FX-426] Disable and clear PIN field on submit

---

Sources/ForageSDK/Component/ForagePANTextField/ForagePANTextField.swift
Sources/ForageSDK/Component/ForagePANTextField/MaskedUITextField.swift
Tests/ForageSDKTests/ForageElementDelegateTests.swift
Tests/ForageSDKTests/ForagePANTextFieldTests.swift
Tests/ForageSDKTests/MaskedUITextFieldTests.swift

Apply dynamic masking to the PAN based on expected card length.
Screen recording: https://joinforage.slack.com/archives/C031SJGSZV0/p1692122220569439
Unit tests to validate the adjusted mask.
can be released as-is. A later PR will make isValid default to true on empty state.

[FX-398] iOS support dynamically updating the mask of ebt card

---

Sources/ForageSDK/Component/ForagePANTextField/MaskedUITextField.swift
Tests/ForageSDKTests/MaskedUITextFieldTests.swift

- Support mask for invalid and special cards (e.g. starts with 9999) when the entered PAN is greater than 16 digits
- use 4 x 4 groups of chars and place the excess digits in the last char group (ex: XXXX XXXX XXXX XXXX XXX)
Screen recording: https://joinforage.slack.com/archives/C031SJGSZV0/p1692738518786379
Client wants to enter more than 16 digits during testing
- Added unit tests

[FX-464] Allow up to 19 digits for invalid + special cards

---

Sources/ForageSDK/Component/ForagePINTextField/Vault/BtPINTextField.swift
Sources/ForageSDK/Component/ForagePINTextField/Vault/VgsPINTextField.swift

Set the PIN field to be centered text.
VGS:
BT:

[FX-469] Set the PIN field to be centered text

---

Sources/ForageSDK/Component/ForagePANTextField/ForagePANTextField.swift
Sources/ForageSDK/Component/ForagePINTextField/Vault/VgsPINTextField.swift

PAN (no letters)
PIN inputs use telephone pad (with letters)
**Remark: when I tested this on iOS 14.0.1 against an iPhone 8., the phone pad still appeared for the PAN field – but this feature seems to work on newer iPhones (tested with iPhone 14 using iOS 16.2)**
Better UX/CX

[FX-486] PAN uses num pad, PINs use phone pad

---

Sources/ForageSDK/Component/ForagePINTextField/ForagePINTextField.swift
Sources/ForageSDK/Component/ForagePINTextField/Protocol/VaultWrapper.swift
Sources/ForageSDK/Component/ForagePINTextField/Vault/BtPINTextField.swift
Sources/ForageSDK/Component/ForagePINTextField/Vault/VgsPINTextField.swift
Tests/ForageSDKTests/ForagePINTextFieldTests.swift

- Enable customization of styling of PIN input border radius and background color.
Default TextField
Custom TextField

[SYM-110] Enable border radius and background color customization

---

Sources/ForageSDK/Foundation/Telemetry/ForageLogger.swift

Add `sdk_version` to Datadog log context/attributes
- [DD logs with `@sdk_version:3.0.7`](https://app.datadoghq.com/logs?query=service%3Aios-sdk%20env%3Astaging%20%40sdk_version%3A3.0.7&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1693251094263&to_ts=1693253039313&live=false)
Help us with monitoring, troubleshooting and tracking which version the client is using

[FX-500] Add sdk_version to logs

---

ForageSDK.podspec
Package.swift
Sources/ForageSDK/ForageSDK.swift

Remove sentry from iOS SDK to avoid crashing GoPuff app

[FX-509] Remove sentry from iOS SDK

---

ForageSDK.podspec
Package.swift

- Update Basis Theory package to v2.8.0
- Which consequently removes [Datadog](https://github.com/DataDog/dd-sdk-ios/) as a dependency from our dependency tree.
https://linear.app/joinforage/issue/FX-514/update-basis-theory-ios-to-v280

[FX-514] Update Basis theory to v2.8.0

---

README.md
Sample/SampleForageSDK/AppDelegate.swift
Sample/SampleForageSDK/Base.lproj/Main.storyboard
Sample/SampleForageSDK/Foundation/Base/ClientSharedData.swift
Sample/SampleForageSDK/Foundation/Network/Model/CreatePaymentRequest.swift
Sample/SampleForageSDK/Foundation/Network/Model/CreatePaymentResponse.swift
Sample/SampleForageSDK/Foundation/Network/Model/ForageCaptureModel.swift
Sample/SampleForageSDK/Foundation/Network/SampleAPI.swift
Sample/SampleForageSDK/Sections/CapturePayment/CapturePaymentView.swift
Sample/SampleForageSDK/Sections/CardNumber/CardNumberView.swift
Sample/SampleForageSDK/Sections/CreatePayment/CreatePaymentView.swift
Sample/SampleForageSDK/Sections/RequestBalance/RequestBalanceView.swift
Sample/SampleForageSDK/ViewController.swift
Sources/ForageSDK/ForageSDK.swift
Sources/ForageSDK/Foundation/ForageSDK+ForageServices.swift
Sources/ForageSDK/Foundation/Network/ForageAPI.swift
Sources/ForageSDK/Foundation/Network/LiveForageService.swift
Sources/ForageSDK/Foundation/Network/Model/ForagePANRequestModel.swift
Sources/ForageSDK/Foundation/Network/Model/PaymentModel.swift
Sources/ForageSDK/Foundation/Network/Protocol/ForageService.swift
Tests/ForageSDKTests/CollectorTests.swift
Tests/ForageSDKTests/FloatingTextFieldTests.swift
Tests/ForageSDKTests/ForageElementDelegateTests.swift
Tests/ForageSDKTests/ForagePANTextFieldTests.swift
Tests/ForageSDKTests/ForagePINTextFieldTests.swift
Tests/ForageSDKTests/ForageServiceTests.swift
Tests/ForageSDKTests/MaskedUITextFieldTests.swift
Tests/ForageSDKTests/ResponseMonitorTests.swift

- Move `merchantAccount` and `bearerToken` from the submit methods to the `ForageSDK.Config`
- Call `ForageSDK.setup()` with the new `ForageSDK.Config` to update the environment, session token, merchant account, and/or bearer token
https://linear.app/joinforage/issue/FX-392/move-merchantaccount-bearertoken-to-foragesdksetup-in-forage-ios-sdk
Opted against using `@available` and gracefully deprecating the old method signatures (make the change reverse compatible), since only one client will have to make this small + trivial change on their end and we're currently making other breaking changes to the SDK anyway.
- Breaking change!
Can be [found in Notion](https://www.notion.so/joinforage/iOS-SDK-Migration-guide-v3-v4-86907ee4b …

[FX-392] Move merchantAccount + bearerToken to Config

---

README.md
Sample/SampleForageSDK/Sections/CardNumber/CardNumberView.swift
Sources/ForageSDK/Component/ForagePANTextField/ForagePANTextField.swift
Sources/ForageSDK/Component/ForagePANTextField/MaskedUITextField.swift
Sources/ForageSDK/ForageSDK.swift
Sources/ForageSDK/Foundation/ForageSDK+ForageServices.swift
Tests/ForageSDKTests/FloatingTextFieldTests.swift
Tests/ForageSDKTests/ForagePANTextFieldTests.swift
Tests/ForageSDKTests/MaskedUITextFieldTests.swift

- Stop saving PAN in a static shared variable
- Allow developer to pass in a `ForagePINTextField` to the SDK
🎥 Screen recording: https://joinforage.slack.com/archives/C031SJGSZV0/p1693358544532169
Co-author: @dleis612
Linear ticket: https://linear.app/joinforage/issue/FX-415/ios-do-not-store-pannumber-in-foragesdkshared
- Allow client to display and use more than one PAN element
Displayed and submitted multiple PAN elements in the sample app, as seen in the [screen recording](https://joinforage.slack.com/archives/C031SJGSZV0/p1693358544532169).
⚠️ Breaking change!
- Should be released with the rest of the PRs in the stack (#60 and #75)
- Supersedes Danny's previous PR: https://github.com/teamforage/forage-ios-sdk/pull/69

[FX-415] Stop storing PAN in ForageSDK.shared

---

README.md
Sample/SampleForageSDK/Sections/CapturePayment/CapturePaymentView.swift
Sample/SampleForageSDK/Sections/RequestBalance/RequestBalanceView.swift
Sample/SampleForageSDK/Sections/RequestBalance/RequestBalanceViewController.swift
Sources/ForageSDK/Foundation/ForageSDK+ForageServices.swift

- Make naming more consistent
- Make parameter position more consistent with `tokenizeEBTCard` and other SDKs (object first, then rest of params)
- Refresh comments (had broken links and missing info
- Update README
https://linear.app/joinforage/issue/FX-511/ios-foragepintextedit-should-be-renamed-to-foragepintextfield
Should be released with the [rest of the PRs in this stack](https://github.com/teamforage/forage-ios-sdk/pull/87#issuecomment-1699370908)

[FX-511] Refactor from textEdit -> textField

---

Tests/ForageSDKTests/CollectorTests.swift
Tests/ForageSDKTests/FloatingTextFieldTests.swift
Tests/ForageSDKTests/ForageElementDelegateTests.swift
Tests/ForageSDKTests/ForagePANTextFieldTests.swift
Tests/ForageSDKTests/ForageSDKTests.swift
Tests/ForageSDKTests/ForageServiceTests.swift
Tests/ForageSDKTests/MaskedUITextFieldTests.swift
Tests/ForageSDKTests/ResponseMonitorTests.swift

- Add unit tests for `ForageSDK.swift`
- Remove `ForageSDK.shared.service = nil` statements [FX-416](https://linear.app/joinforage/issue/FX-416/ios-remove-foragesdksharedservice-=-nil-statements-from-tests)
- helps ensure the rest of the changes in this PR stack work and reduce the risk of regressions
- helps ensure logger is initialized, which is not covered by our E2E tests.
Can be released as-is, with the rest of the PRs in this stack.

[FX-512] Add ForageSDK.swift unit tests

---

.slather.yml
Sources/ForageSDK/Foundation/Network/LDManager.swift
Sources/ForageSDK/Foundation/Telemetry/ForageLogger.swift
Sources/ForageSDK/Foundation/Telemetry/NoopLogger.swift
Tests/ForageSDKTests/LDManagerTests.swift

- Remove use of [force unwrapping the LDCient, which can lead to crashes](https://www.hackingwithswift.com/sixty/10/4/force-unwrapping)
- instead, we fallback to VGS and allow the show to go on.
- Add unit tests for LDManager
- Do a bit of refactoring to allow for testing via dependency injection and for better readability
- Add logs to catch LaunchDarkly related errors
- Crashproofing the iOS SDK
- Reliability
- Getting to > 80% unit test coverage
Can be released as-is in the next release

[FX-494] Make LDManager safer

---

Sample/SampleForageSDK/Sections/CapturePayment/CapturePaymentView.swift
Sources/ForageSDK/Foundation/Network/LiveForageService.swift
Sources/ForageSDK/Foundation/Network/Model/ForageErrorModel.swift
Sources/ForageSDK/Foundation/Network/Model/MessageResponseModel.swift

- Add support for `ForageErrorObj.details` 
- Add helpful comments to error structs, to improve dev experience and reduce integration time
- Show details in payment capture page
- Reduce duplication in sample app payment capture page
https://linear.app/joinforage/issue/FX-529/ios-expose-details-field-for-forageerror
Used this [test card](https://docs.joinforage.app/docs/test-ebt-cards#:~:text=Expired%20card-,4444444444444451,-Insufficient%20funds) to force insufficient funds error
Created [this ticket](https://linear.app/joinforage/issue/FX-532/ios-add-e2e-test-assertion-for-error-details-on-insufficient-funds) to add e2e tests for covering this change.
Can share the following snippet with GoPuff for …

[FX-529] Add support for error details

---

README.md
Sample/SampleForageSDK/Sections/RequestBalance/RequestBalanceView.swift
Sources/ForageSDK/Component/ForagePINTextField/ForagePINTextField.swift
Sources/ForageSDK/Component/ForagePINTextField/Protocol/VaultWrapper.swift
Sources/ForageSDK/Component/ForagePINTextField/Vault/BtPINTextField.swift
Sources/ForageSDK/Component/ForagePINTextField/Vault/VgsPINTextField.swift
Sources/ForageSDK/Foundation/Protocol/ForageElement.swift
Tests/ForageSDKTests/ForagePINTextFieldTests.swift

Expose PIN fields so that GoPuff doesn't need to hack to set the values.
BT:
VGS:

[FX-535] iOS expose cornerradius and maskstobound for pin

---

Sample/SampleForageSDK/Sections/CapturePayment/CapturePaymentView.swift
Sample/SampleForageSDK/Sections/RequestBalance/RequestBalanceView.swift
Sources/ForageSDK/Component/ForagePANTextField/ForagePANTextField.swift
Sources/ForageSDK/Component/ForagePINTextField/ForagePINTextField.swift
Sources/ForageSDK/Component/ForagePINTextField/Protocol/VaultWrapper.swift
Sources/ForageSDK/Component/ForagePINTextField/Vault/BtPINTextField.swift
Sources/ForageSDK/Component/ForagePINTextField/Vault/VgsPINTextField.swift
Sources/ForageSDK/Foundation/Protocol/ForageElement.swift
Tests/ForageSDKTests/ForagePANTextFieldTests.swift
Tests/ForageSDKTests/ForagePINTextFieldTests.swift

- Enable customization of styling of PIN input width and height

[SYM-109] Enable customization of styling of PIN input width and height

---

Sources/ForageSDK/Component/ForagePANTextField/ForagePANTextField.swift
Sources/ForageSDK/Component/ForagePINTextField/ForagePINTextField.swift
Sources/ForageSDK/Component/ForagePINTextField/Protocol/VaultWrapper.swift
Sources/ForageSDK/Component/ForagePINTextField/Vault/BtPINTextField.swift
Sources/ForageSDK/Component/ForagePINTextField/Vault/VgsPINTextField.swift
Sources/ForageSDK/Foundation/Protocol/ForageElement.swift

- Remove redundant `setPlaceholderText`
- https://linear.app/joinforage/issue/FX-547/bug-setplaceholdertext-is-not-implemented
- I could have deprecated this method and removed it gracefully, but no one is/should be using this method
Can be released as-is. Technically a breaking change, but given no one is/should have been using this redundant method – it is safe to remove.

[FX-547] Remove setPlaceholderText

---

Sources/ForageSDK/Foundation/ForageSDK+ForageServices.swift
Sources/ForageSDK/Foundation/Network/Utils/Constants.swift

When a user tries to submit a PIN of an invalid length, we can respond immediately with a user_error.
I tested this locally and will be adding a qa-test for the behavior!

[FX-594] Respond with user_error if invalid PIN is submitted

---

Sample/SampleForageSDK/Sections/RequestBalance/RequestBalanceView.swift
Sources/ForageSDK/Component/ForagePINTextField/ForagePINTextField.swift
Sources/ForageSDK/Component/ForagePINTextField/Vault/BtPINTextField.swift
Sources/ForageSDK/Component/ForagePINTextField/Vault/VgsPINTextField.swift

Remove hard height constraint set on our internal PIN fields. 
I implemented the ForagePINTextField identically to how GoPuff does in our BalanceRequestPage in the sample app. I show how the current implementation blocks the height value that they are applying at the highest level and how loosening the constraint has the desired outcome.
https://github.com/teamforage/forage-ios-sdk/assets/89605898/74acc7f6-f125-48cc-ad01-94e3bad0fd43

[FX-605] Remove constant height constraint

---

Sample/SampleForageSDK/Sections/RequestBalance/RequestBalanceView.swift
Sources/ForageSDK/Foundation/Network/Model/PaymentModel.swift
Tests/ForageSDKTests/ForageServiceTests.swift

Make the balance object on the receipt field nullable. Currently, we throw a parsing error if a user attempts to test the lost card multiple times in production. If a payment capture fails, we do a GET for the Payment and there are times when there is no available `balance` for the card.
I was able to recreate GoPuff's error locally and was able to solve the issue with this fix.

[FX-618] Make the balance field nullable to avoid throwing error

---

Sources/ForageSDK/Foundation/ForageSDK+ForageServices.swift
Sources/ForageSDK/Foundation/Network/Collector.swift
Sources/ForageSDK/Foundation/Network/LiveForageService.swift
Sources/ForageSDK/Foundation/Telemetry/CustomerPerceivedResponseMonitor.swift
Sources/ForageSDK/Foundation/Telemetry/ResponseMonitor.swift
Sources/ForageSDK/Foundation/Telemetry/VaultProxyResponseMonitor.swift
Tests/ForageSDKTests/ResponseMonitorTests.swift

- Add customer-perceived response metrics to `checkBalance` and `capturePayment`
https://linear.app/joinforage/issue/FX-572/ios-include-customer-perceived-metric-in-monitoring
- PATCH-level change
- Will follow-up with a cleanup PR for `checkBalance` and `capturePayment` ([FX-631](https://linear.app/joinforage/issue/FX-631/ios-clean-up-checkbalance-and-capturepayment))

[FX-572] Add customer-perceived response metrics

---

Sample/SampleForageSDK/Sections/CapturePayment/CapturePaymentView.swift
Sample/SampleForageSDK/Sections/RequestBalance/RequestBalanceView.swift
Sources/ForageSDK/Component/ForagePINTextField/Vault/BtPINTextField.swift
Tests/ForageSDKTests/ForagePINTextFieldTests.swift

- Temp workaround for https://linear.app/joinforage/issue/FX-622/bug-make-basis-theory-pin-cleartext-not-crash-in-ios
- Clean up how we display error details in sample app
https://linear.app/joinforage/issue/FX-622/bug-make-basis-theory-pin-cleartext-not-crash-in-ios
- Added unit tests for clearText
- Call `clearText` in sample app
This change will ideally be [followed by a "full" fix once Basis Theory releases an official](https://linear.app/joinforage/issue/FX-622/bug-make-basis-theory-pin-cleartext-not-crash-in-ios#comment-1f9863a8) `clearText` method.

[FX-622] Add temp workaround for clearText BT bug

---

Sample/SampleForageSDK/Foundation/Network/Provider.swift
Sources/ForageSDK/Component/ForagePINTextField/ForagePINTextField.swift
Sources/ForageSDK/ForageSDK.swift
Sources/ForageSDK/Foundation/Network/ForageAPI.swift
Sources/ForageSDK/Foundation/Network/LDManager.swift
Sources/ForageSDK/Foundation/Network/LiveForageService.swift
Sources/ForageSDK/Foundation/Network/Protocol/Polling.swift
Sources/ForageSDK/Foundation/Network/Provider.swift
Tests/ForageSDKTests/ForageServiceTests.swift
Tests/ForageSDKTests/LDManagerTests.swift

Adding +/- 25ms jitter to polling so that we can avoid a thundering herd issue if our clients retry all at the same time. Now all retries to polling will have some randomness added to their delay interval.

[POP-180] Adding jitter to retry logic

---

Sources/ForageSDK/Component/ForagePINTextField/ForagePINTextField.swift
Sources/ForageSDK/Foundation/ForageSDK+ForageServices.swift
Sources/ForageSDK/Foundation/Network/Collector.swift
Sources/ForageSDK/Foundation/Network/LiveForageService.swift
Sources/ForageSDK/Foundation/Network/Model/ForageErrorModel.swift
Sources/ForageSDK/Foundation/Network/Model/ForageRequestModel.swift
Sources/ForageSDK/Foundation/Network/Protocol/ForageService.swift
Sources/ForageSDK/Foundation/Network/Protocol/Polling.swift
Sources/ForageSDK/Foundation/Network/Utils/Constants.swift

- Introduce use of async await (compatible with Swift v5.5, which [we use](https://github.com/teamforage/forage-ios-sdk/blob/95864356d1e840e411cfbfc77d367ad962cd5cb3/Package.swift#L1-L2)) to break the deep nesting of switch statements across the method chain for `checkBalance` and `capturePayment`
- Introduce `submitPinToVault` [method](https://github.com/teamforage/forage-ios-sdk/blob/95864356d1e840e411cfbfc77d367ad962cd5cb3/Sources/ForageSDK/Foundation/Network/LiveForageService.swift#L251-L252) to reduce duplication across checkBalance and capturePayment
- De-dupe calls to `monitor.end()`; [Previous state](https://github.com/teamforage/forage-ios-sdk/blob/9316d96bbd98f72c0eebdbe5e6f9d5d0987ba825/Sources/ForageSDK/Foundation/ForageSDK%2BForageServices.swift#L187-L233)
- De-dupe PIN …

[FX-631] Clean up checkBalance and capturePayment

---

Sources/ForageSDK/ForageSDK.swift
Sources/ForageSDK/Foundation/Network/LiveForageService.swift
Sources/ForageSDK/Foundation/Network/LivePollingService.swift
Sources/ForageSDK/Foundation/Network/Model/MessageResponseModel.swift
Sources/ForageSDK/Foundation/Network/PollingService.swift
Sources/ForageSDK/Foundation/Network/Protocol/Polling.swift
Sources/ForageSDK/Foundation/Network/Utils/Concurrency.swift
Tests/ForageSDKTests/ForageServiceTests.swift
Tests/ForageSDKTests/LDManagerTests.swift
Tests/ForageSDKTests/Mock/ForageMocks.swift
Tests/ForageSDKTests/Mock/MockLogger.swift
Tests/ForageSDKTests/Mock/TestUtils.swift
Tests/ForageSDKTests/PollingServiceTests.swift

- Move `Polling` to its own service; the `LiveForageService.swift` file was dealing with too many concerns and was hard to test
- Add unit tests for `Polling`
- Return `ForageError` for polling errors, where we were previously returning string errors to the client.
https://linear.app/joinforage/issue/FX-480/add-unit-tests-for-ios-polling
- ✅  Added an exhaustive suite of unit tests for `Polling`

[FX-480] Add Polling unit tests

---

.github/workflows/qa-tests.yaml
Sample/fastlane/Fastfile

Use custom ID when the job is running against a PR or manual run (workflow_dispatch)
- Pass `custom_id` to fastlane and mobile-qa-tests
Prevent [CI check concurrency issues](https://joinforage.slack.com/archives/C066KCQ5QSW/p1702436741682179?thread_ts=1702419846.399839&cid=C066KCQ5QSW)
- Use `custom_id` when deploying the sample app and when running QA tests.
There will be a separate PR in the mobile-qa-tests that consumes the `customer_id` environment var

[FX-838] Prevent concurrency issues for QA test runs

---

Sources/ForageSDK/Foundation/ForageSDK+ForageServices.swift
Sources/ForageSDK/Foundation/Telemetry/CustomerPerceivedResponseMonitor.swift
Sources/ForageSDK/Foundation/Telemetry/ResponseMonitor.swift
Tests/ForageSDKTests/ForagePublicSubmitMethodTests.swift
Tests/ForageSDKTests/ForageSDKTests.swift
Tests/ForageSDKTests/Mock/MockForageSDK.swift
Tests/ForageSDKTests/Mock/MockLogger.swift
Tests/ForageSDKTests/PollingServiceTests.swift

- Pass "origin" logger to metrics/monitor service
- Reject with error instead of assertionFailure
- Adds unit tests for "Public submit methods" (tokenizeEBTCard, checkBalance, capturePayment)
https://linear.app/joinforage/issue/FX-728/add-ios-unit-tests-for-foragesdkforagesdkservice-extension
- ✅ Added unit tests
Can be released as-is, will be used to facilitate testing for #131

[FX-728] Add ForageSDK+ForageServices unit tests

---

README.md
Sample/SampleForageSDK/Foundation/Base/BaseSampleView.swift
Sample/SampleForageSDK/Sections/CapturePayment/CapturePaymentView.swift
Sample/SampleForageSDK/Sections/CardNumber/CardNumberView.swift
Sample/SampleForageSDK/Sections/RequestBalance/RequestBalanceView.swift
Sources/ForageSDK/Foundation/Network/Model/ForageErrorModel.swift
Sources/ForageSDK/Foundation/Network/PollingService.swift
Sources/ForageSDK/Foundation/Network/Provider.swift
Sources/ForageSDK/Foundation/Network/Utils/Constants.swift
Sources/ForageSDK/Foundation/Telemetry/ResponseMonitor.swift
Tests/ForageSDKTests/ForagePublicSubmitMethodTests.swift

ℹ️ The new `ForageError` format also orders the parameters in order of usage popularity:
1. code
2. httpStatusCode
3. message
4. details
https://linear.app/joinforage/issue/FX-933/ios-support-single-error-for-client-facing-errors
- ✅ Updated unit tests
- ✅ Updated sample app
- ✅ Did some manual verification across edge cases like forage errors with `details` (ebt_error_51)
Have to bump `MINOR` version level of the associated release.

[FX-933] Add support for single ForageError

---

Sources/ForageSDK/Foundation/Network/LiveForageService.swift

- Will add unit + e2e tests to cover this
release ASAP, to deprecate v4.4.0 release and bump to 4.4.1

[FX-964] Use paymentRef for idempotency-key on capturePayment and deferPaymentCapture

---

ForageSDK.podspec
Package.swift

Because of the optimistic operator we are seeing build failures on our automated CI tests run on main. VGS released version 1.16.0 yesterday which seems to be causing the issue. Our tests passed on the version before, which is 1.15.3.

Pin the VGS Collect package to avoid build failures in CI

---

Sources/ForageSDK/Foundation/Network/ForageAPI.swift
Sources/ForageSDK/Foundation/Network/LiveForageService.swift

Add a default version header to all endpoints in the SDK to avoid backwards compatibility behavior that can be introduced by setting an API version header in the dashboard.
Let QA tests run.

[FX-1183] Pin all endpoints that don't require a version to default

---

Sample/SampleForageSDK/Sections/RequestBalance/RequestBalanceView.swift
Sources/ForageSDK/Component/ForagePINTextField/ForagePINTextField.swift

-  Mark setting `foragePinTextField.placeholder` as deprecated
- `foragePanTextField.placholder` is still supported
- UX
- `pin.placeholder` was a no-op prior to this change

[FX-1274] Mark pinTextField.placeholder as deprecated

---

Sources/ForageSDK/Foundation/Network/Collector.swift
Sources/ForageSDK/Foundation/Network/LiveForageService.swift
Sources/ForageSDK/Foundation/Network/Model/ForageErrorModel.swift
Sources/ForageSDK/Foundation/Network/Model/PaymentModel.swift
Sources/ForageSDK/Foundation/Network/Protocol/ForageService.swift
Tests/ForageSDKTests/CollectorTests.swift
Tests/ForageSDKTests/ForagePublicSubmitMethodTests.swift
Tests/ForageSDKTests/Mock/TestUtils.swift

- Refactor all vault submissions to optimize DRY
- Separate vault concerns from ForageSDK concerns
- Add unit tests for the handling of both VGS and BT responses
-- We currently don't handle error responses correctly in the BT flow for the iOS SDK and this fixes that issue

Further refactoring work

---

Sources/ForageSDK/Foundation/Network/LiveForageService.swift
Sources/ForageSDK/Foundation/Network/Model/PaymentModel.swift
Sources/ForageSDK/Foundation/Network/Protocol/ForageService.swift
Tests/ForageSDKTests/ForageServiceTests.swift

- Only grab "necessary info" for the "preliminary" /GET/ payment calls
- Included comments for context + posterity
- https://linear.app/joinforage/issue/FX-1362/only-grab-required-info-for-internal-preliminary-get-payment-calls
- ✅ Tested locally ; @dleis612 is adding corresponding automated E2E tests
- Updated unit tests
Should be released ASAP

[FX-1362] Only grab the payment_method ref from the ThinPayment

---

Sources/ForageSDK/Foundation/Network/LiveForageService.swift

Part of MMF project and PCI-Compliance:
- **pass through session-token as header in vault calls** (this PR)
- **enforce merchantId for Forage client initialization** - should already be done (since the documentation specifies they should use the merchantID starting with mid/ to start the client, but we need to verify that's currently being done before enforcing validation on the field, in case someone is still using fns
- In sample app, make balance check calls to VGS / BT, confirm that the calls go through successfully
- In datadog, confirm that the headers are being passed in to us [here](https://app.datadoghq.com/logs?query=env%3Adev%20service%3Aios-sdk%20OR%20trace_id%3A3345885844225900%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAY-CmUlvx1FojwAAAAAAAAAYA …

Pass Session-Token through to vault calls

---

Sources/ForageSDK/Foundation/ForageSDK+ForageServices.swift
Sources/ForageSDK/Foundation/Telemetry/CustomerPerceivedResponseMonitor.swift
Tests/ForageSDKTests/ForagePublicSubmitMethodTests.swift
Tests/ForageSDKTests/Mock/MockLogger.swift

The current iOS logs are pretty good. We store a ton of relevant data in the `customer_perceived_response` log that can be used to build monitoring. I would argue that we may not need to "error" when the http response code is in the 400s.

[1493] Only log errors when the response code is in the 500s

---

Sources/ForageSDK/Component/ForagePINTextField/Vault/RosettaPINTextField.swift
Tests/ForageSDKTests/ForagePINTextFieldTests.swift
Tests/ForageSDKTests/ResponseMonitorTests.swift

Fixes an issue where `isFirstResponder` on `RosettaPINTextField` wasn't getting updated properly when the underlying UITextField was focused or unfocused. Also adds a test for this.
Also fixes an issue with the Response Monitor unit tests that was introduced in https://github.com/teamforage/forage-ios-sdk/pull/170
https://linear.app/joinforage/issue/FX-1509/fix-isfirstresponder-state-update
Manually verified the state updates in the sample app, also added a unit test.
Can be merged as-is

[FX-1509] Fix isFirstResponder state update in rosetta PIN input

---

ForageSDK.podspec
Package.swift

Bumps LD to 9.6.1
https://linear.app/joinforage/issue/FX-1520/update-forage-sdk-dependency-to-version-961-to-resolve-resource-issue
- ❌ Not a front-end change
- ❌ iOS QA Tests passed locally - created PR on github
- ❌ Unit Tests passed locally - created PR on github
Can be rolled out as is, pending approval and passing tests

[FX-1520] Bump LD to 9.6.1

---

Sources/ForageSDK/ForageSDK.swift
Sources/ForageSDK/Foundation/Telemetry/ForageLogger.swift
Tests/ForageSDKTests/ForageSDKTests.swift

- Conventionally, merchants use `updateMerchantID` and `updateSessionToken`
Should be released ASAP! The `ForageSDK.swift` class could use a lot of TLC 😅 , but this is a stopgap solution

[FX-1598] Make setup update merchant ID + session token

---

Sources/ForageSDK/ForageSDK.swift
Tests/ForageSDKTests/FloatingTextFieldTests.swift
Tests/ForageSDKTests/MaskedUITextFieldTests.swift

Refactors some of the instance properties (merchantId, sessionToken, etc.) in `ForageSDK` to be derived from their static counterparts rather than be mutable, manually-set values. 
This guarantees the instance values in the `shared` singleton are always synced to what's in the static `config` property.
Reduces the likelihood of us forgetting to update something and creating unexpected issues.
- ✅ Not a front-end change
Can be safely merged into the `evan/sdk-hardening` branch, where I'm building up some refactoring changes.

Refactor instance properties in ForageSDK to avoid manually syncing values

---

.github/workflows/qa-tests.yaml

This PR is a **short-term fix** that updates the GitHub Actions workflow for the QA Tests job to explicitly use Python 3.12. The **longer-term fix** would be to bump the version of `ddtrace` to the release that contains [their PR for supporting Python 3.13](https://github.com/MatthieuDartiailh/bytecode/pull/146).
The CI jobs began [failing three days ago](https://github.com/teamforage/forage-ios-sdk/actions/runs/11531602539), with errors during the wheel-building process for `ddtrace`. An investigation revealed that the GitHub Action runners had recently [bumped versions from Python 3.12 -> Python 3.13](https://github.com/actions/runner-images/releases/tag/macos-13%2F20241023.237#:~:text=24.2%20(python%203.12)-,24.2%20(python%203.13),-RubyGems). Datadog has a PR out that allows `ddtrace` …

Update QA-tests to expressly use Python 3.12

---

.github/workflows/Coverage.yaml

Update Coverage.yaml to use iPhone 15 instead of iPhone 14
iPhone 14 appears no longer available. I don't know how that broke all of a sudden. Maybe pinning the version of Python or something else could help.
I choose iPhone 15 because it was available when running `xcrun simctl list devices`
The Coverage check passes.
Can be merged in once approved.

Run Coverage with iPhone 15

---

Sources/ForageSDK/Foundation/Network/Provider.swift
Tests/ForageSDKTests/ForagePublicSubmitMethodTests.swift
Tests/ForageSDKTests/ForageServiceTests.swift
Tests/ForageSDKTests/Mock/ForageMocks.swift
Tests/ForageSDKTests/Mock/URLSessionDataTaskMock.swift

Credit to [cltnschlosser](https://github.com/cltnschlosser) for this PR.
Update tests and `Provider.swift` to prevent multiple continuation resume calls. Also removed unused code to reduce maintenance burden.
Multiple calls to resume a continuation caused runtime exceptions, which should not happen
Updated relevant tests to assert that continuation resume is never called more than once. Also added a few other test cases.
- ✅  Not a front-end change
- ❌ iOS QA Tests passed locally - I didn't run them locally but the QA test check passes
- ✅  Unit Tests passed locally - yes, and the coverage check runs the tests and they pass
Can be merged right away

Prevent multiple continuation resume calls
