teamforage/forage-ios-sdk

- Sources/ForageSDK/Foundation/Network/ForageService.swift
Ticket: [SYM-69](https://linear.app/joinforage/issue/SYM-69/[ios]-generate-a-unique-idempotency-key-for-balance-check)
Update the idempotency key on check balance to generate a UUID for each request
> [SYM-69] Idempotency key

- ForageSDK.podspec
- Distribute SDK using CocoaPods
> [SYM-68] Cocoapods support

- README.md
Update README to add cocoapod integration
> Add Cocoapod integration on doc

- Sources/ForageSDK/Component/ForagePANTextField/ForagePANTextField.swift
- Sources/ForageSDK/Component/ForagePINTextField/ForagePINTextField.swift
Add new checks for entering only digits on text fields
> Numbers only

- Sources/ForageSDK/ForageSDK.swift
Disable VGS logs to all environments
> Disable all VGS logs

- Sources/ForageSDK/ForageSDK.swift
> Update env selected

- Sample/SampleForageSDK/Foundation/Base/BaseViewCodeViewController.swift
Ticket: [SYM-85](https://linear.app/joinforage/issue/SYM-85/[ios]-handler-for-keyboard)
- Dismiss keyboard touching outside the keyboard
> [SYM-85] Dismiss keyboard

- Sample/SampleForageSDK/Base.lproj/Main.storyboard
- Sample/SampleForageSDK/Sections/CapturePayment/CapturePaymentView.swift
- Sample/SampleForageSDK/Sections/CardNumber/CardNumberView.swift
- Sample/SampleForageSDK/Sections/CreatePayment/CreatePaymentView.swift
- Sample/SampleForageSDK/Sections/RequestBalance/RequestBalanceView.swift
Ticket: [SYM-92](https://linear.app/joinforage/issue/SYM-92/[ios]-add-accessibility-identifier)
- Add accessibility identifier for QA automation
> [SYM-92] Add accessibility identifier

- README.md
- Sample/SampleForageSDK/Sections/CapturePayment/CapturePaymentView.swift
- Sample/SampleForageSDK/Sections/CardNumber/CardNumberView.swift
- Sources/ForageSDK/Component/ForagePANTextField/ForagePANValidations.swift
- Sources/ForageSDK/Component/ForagePANTextField/Protocol/ForagePANTextFieldDelegate.swift
- Sources/ForageSDK/Component/ForagePINTextField/Protocol/ForagePINTextFieldDelegate.swift
- Sources/ForageSDK/ForageSDK.swift
- Sources/ForageSDK/Foundation/ForageSDK+ForageServices.swift
- Sources/ForageSDK/Foundation/Network/ForageAPI.swift
- Sources/ForageSDK/Foundation/Network/ForageService.swift
- Sources/ForageSDK/Foundation/Network/LiveForageService.swift
- Sources/ForageSDK/Foundation/Network/Model/ForagePANRequestModel.swift
- Sources/ForageSDK/Foundation/Network/Model/ForageRequestModel.swift
- Sources/ForageSDK/Foundation/Network/Model/ForageXKeyModel.swift
- Sources/ForageSDK/Foundation/Network/Model/MessageResponse.swift
- Sources/ForageSDK/Foundation/Network/Protocol/ForageService.swift
- Sources/ForageSDK/Foundation/Network/Protocol/Polling.swift
Tickets: 
[SYM-80](https://linear.app/joinforage/issue/SYM-80/[ios]-polish-polling-solution)
[SYM-89](https://linear.app/joinforage/issue/SYM-89/[ios]-create-descriptive-documentation)
- Separate responsibilities;
- Break down files;
- Create descriptive documentation on functions;
> [SYM-80][SYM-89] Polish implementation

- Sources/ForageSDK/Component/ForagePANTextField/ForagePANTextField.swift
- Sources/ForageSDK/Component/ForagePINTextField/ForagePINTextField.swift
Tickets: 
[SYM-93](https://linear.app/joinforage/issue/SYM-93/[ios]-add-accessibility-identifier-to-forage-component)
- Add accessibility identifier to Forage components
> [SYM-93] Add accessibility identifier to Forage components

- Sample/SampleForageSDK/Sections/CapturePayment/CapturePaymentView.swift
- Sample/SampleForageSDK/Sections/CardNumber/CardNumberView.swift
- Sample/SampleForageSDK/Sections/CreatePayment/CreatePaymentView.swift
- Sample/SampleForageSDK/Sections/RequestBalance/RequestBalanceView.swift
Tickets: [SYM-95](https://linear.app/joinforage/issue/SYM-95/[ios]-separate-elements-for-testing)
- Break down elements for automation to get each values separated
> [SYM-95] Breakdown elements

- Sample/SampleForageSDK/Foundation/Network/Provider.swift
- Sample/SampleForageSDK/Sections/CapturePayment/CapturePaymentView.swift
- Sample/SampleForageSDK/Sections/CardNumber/CardNumberView.swift
- Sample/SampleForageSDK/Sections/CreatePayment/CreatePaymentView.swift
- Sample/SampleForageSDK/Sections/RequestBalance/RequestBalanceView.swift
- Sources/ForageSDK/Component/ForagePANTextField/ForagePANTextField.swift
- Sources/ForageSDK/Foundation/Network/ForageService.swift
- Sources/ForageSDK/Foundation/Network/Provider.swift
- Sources/ForageSDK/Foundation/Network/Utils/ForageError.swift
Ticket: [SYM-96](https://linear.app/joinforage/issue/SYM-96/[ios]-retrieve-error-object-from-data-object)
- Handle error when it gets retrieve inside the data object
> [SYM-96] Handling errors on data object

- Sample/SampleForageSDK/Sections/CapturePayment/CapturePaymentView.swift
- Sample/SampleForageSDK/Sections/CardNumber/CardNumberView.swift
- Sample/SampleForageSDK/Sections/CreatePayment/CreatePaymentView.swift
- Sample/SampleForageSDK/Sections/RequestBalance/RequestBalanceView.swift
- Sources/ForageSDK/Component/ForagePANTextField/ForagePANTextField.swift
- Sources/ForageSDK/Component/ForagePINTextField/ForagePINTextField.swift
Ticket: [SYM-97](https://linear.app/joinforage/issue/SYM-97/[ios]-enable-accessibility-element)
- Enable accessibility element that indicates whether the element is an accessibility element that an assistive app can access.
> [SYM-97] Enable accessibility element

- Sample/SampleForageSDK/Sections/CapturePayment/CapturePaymentView.swift
- Sample/SampleForageSDK/Sections/CardNumber/CardNumberView.swift
- Sample/SampleForageSDK/Sections/CreatePayment/CreatePaymentView.swift
- Sample/SampleForageSDK/Sections/RequestBalance/RequestBalanceView.swift
- Sources/ForageSDK/Component/ForagePANTextField/ForagePANTextField.swift
- Sources/ForageSDK/Component/ForagePINTextField/ForagePINTextField.swift
Ticket: [SYM-99](https://linear.app/joinforage/issue/SYM-99/[ios]-remove-accessibility-label)
Remove accessibilityLabel to avoid override label text
> [SYM-99] Remove accessibility label

- ForageSDK.podspec
- Sources/ForageSDK/Component/ForagePANTextField/ForagePANTextField.swift
- Sources/ForageSDK/Component/ForagePINTextField/ForagePINTextField.swift
- Sources/ForageSDK/Foundation/Extension/AssetsBundle.swift
Ticket: [SYM-101](https://linear.app/joinforage/issue/SYM-101/[ios]-create-bundle-to-load-image-on-pod)
- Create a bundle to load image
- Update cocoapods version
> [SYM-101] Create bundle to load image on pods

- Sample/SampleForageSDK/Sections/CardNumber/CardNumberView.swift
- Sources/ForageSDK/Foundation/ForageSDK+ForageServices.swift
- Sources/ForageSDK/Foundation/Network/ForageAPI.swift
- Sources/ForageSDK/Foundation/Network/LiveForageService.swift
- Sources/ForageSDK/Foundation/Network/Model/ForagePANRequestModel.swift
- Sources/ForageSDK/Foundation/Network/Model/ForagePANResponseModel.swift
- Sources/ForageSDK/Foundation/Network/Model/ForageRequestModel.swift
- Sources/ForageSDK/Foundation/Network/Model/MessageResponse.swift
- Sources/ForageSDK/Foundation/Network/Protocol/ForageService.swift
- Sources/ForageSDK/Foundation/Network/Provider.swift
- Sources/ForageSDK/Foundation/Network/Utils/ForageError.swift
- Tests/ForageSDKTests/ForageServiceTests.swift
I updated the client API endpoints to more properly handle error scenarios and respond to the user in a uniform manor.
This change was necessary to give the developer a better experience when integrating Forage and to improve readability.
> Improve error response handlers

- .github/pull_request_template.md
Updated the PR template in this repo to mention that testing must be completed locally before merging.
> [FOR-2036] Update PR template

- README.md
- Sample/SampleForageSDK/Foundation/Base/ClientSharedData.swift
- Sample/SampleForageSDK/Foundation/Network/Model/Address.swift
- Sample/SampleForageSDK/Foundation/Network/Model/CreatePaymentRequest.swift
- Sample/SampleForageSDK/Foundation/Network/Model/ForageBalanceModel.swift
- Sample/SampleForageSDK/Foundation/Network/Model/ForageCaptureModel.swift
- Sample/SampleForageSDK/Foundation/Network/Model/ForagePANModel.swift
- Sample/SampleForageSDK/Foundation/Network/SampleAPI.swift
- Sample/SampleForageSDK/Sections/CardNumber/CardNumberView.swift
- Sample/SampleForageSDK/Sections/CreatePayment/CreatePaymentView.swift
- Sources/ForageSDK/Foundation/ForageSDK+ForageServices.swift
- Sources/ForageSDK/Foundation/Network/ForageAPI.swift
- Sources/ForageSDK/Foundation/Network/Model/ForagePANRequestModel.swift
- Sources/ForageSDK/Foundation/Network/Model/PaymentMethodModel.swift
- Tests/ForageSDKTests/ForageServiceTests.swift
- Tests/ForageSDKTests/Mock/ForageMocks.swift
- Refactor `userID` -> `customerID`
- Refactor `user_id` -> `customer_id`
- Refactor `<x>UserID` -> `<x>CustomerID`
- Refactor `user id` -> `customer id`
- Refactor `user-id` -> `customer-id`
https://linear.app/joinforage/issue/FOR-2012/refactor-userid-customerid-in-forage-android-sdk
Once @tuxtitlan deploys changes in the payments API to dev, we can update the API-VERSION as needed and ensure that customer ID works the same way as it did in #36
> [FOR-2012] Rename userID -> customerID

- Sample/SampleForageSDK/Foundation/Network/SampleAPI.swift
- Sources/ForageSDK/Foundation/Network/ForageAPI.swift
☝️ 
[COR-36](https://linear.app/joinforage/issue/COR-36/update-the-version-name-across-the-board-to-reflect-the-api-release)
- ❌ Not a front-end change
- ❌ iOS QA Tests passed locally
- ❌ Unit Tests passed locally
> [COR-36] Update to actual customer ID release version name

- Sources/ForageSDK/Foundation/Network/LDManager.swift
- Add service context for vault evaluation
- Allows us to control rollout per client by evaluating based on the flag belonging to the client
> Add LD context for evaluation

- README.md
- Sample/SampleForageSDK/Sections/CardNumber/CardNumberView.swift
- Sample/SampleForageSDK/Sections/CardNumber/CardNumberViewController.swift
- Sample/SampleForageSDK/Sections/RequestBalance/RequestBalanceView.swift
- Sources/ForageSDK/Component/ForagePANTextField/ForagePANTextField.swift
- Sources/ForageSDK/Component/ForagePINTextField/ForagePINTextField.swift
- Sources/ForageSDK/Component/ForagePINTextField/Vault/BtPINTextField.swift
- Sources/ForageSDK/Component/ForagePINTextField/Vault/VgsPINTextField.swift
- Sources/ForageSDK/Foundation/ForageSDK+ForageServices.swift
- Tests/ForageSDKTests/ForagePANTextFieldTests.swift
- Tests/ForageSDKTests/ForagePINTextFieldTests.swift
Implement all state properties and link up `onTextChanged` event handlers.
Add a unit test for the event handler and update the qa-tests to check for state changes based on event handlers.
https://github.com/teamforage/forage-ios-sdk/assets/89605898/14cc11cf-07bf-4e48-9191-2ff8cd76a3c3
> [FX-372] Expose input changed event handler for PIN

- ForageSDK.podspec
- Package.swift
Increment the BT package to resolve the DD package collision.
> [FX-424] Increment BT package and Forage to 3.0.3

- .github/workflows/validations.yaml
Add a lint workflow for pull requests for baseline static analysis
> Add lint workflow

- README.md
- Sample/SampleForageSDK/AppDelegate.swift
- Sample/SampleForageSDK/Base.lproj/Main.storyboard
- Sample/SampleForageSDK/Foundation/Base/ClientSharedData.swift
- Sample/SampleForageSDK/Foundation/Network/Model/CreatePaymentRequest.swift
- Sample/SampleForageSDK/Foundation/Network/Model/CreatePaymentResponse.swift
- Sample/SampleForageSDK/Foundation/Network/Model/ForageCaptureModel.swift
- Sample/SampleForageSDK/Foundation/Network/SampleAPI.swift
- Sample/SampleForageSDK/Sections/CreatePayment/CreatePaymentView.swift
- Sample/SampleForageSDK/ViewController.swift
- Sources/ForageSDK/ForageSDK.swift
- Sources/ForageSDK/Foundation/ForageSDK+ForageServices.swift
- Sources/ForageSDK/Foundation/Network/ForageAPI.swift
- Sources/ForageSDK/Foundation/Network/LiveForageService.swift
- Sources/ForageSDK/Foundation/Network/Model/ForagePANRequestModel.swift
- Sources/ForageSDK/Foundation/Network/Model/PaymentModel.swift
- Sources/ForageSDK/Foundation/Network/Protocol/ForageService.swift
- Tests/ForageSDKTests/CollectorTests.swift
- Tests/ForageSDKTests/ForagePANTextFieldTests.swift
- Tests/ForageSDKTests/ForagePINTextFieldTests.swift
- Tests/ForageSDKTests/ForageServiceTests.swift
Refactor config names
- bearerToken -> sessionToken
- merchantAccount -> merchantID
- update mention of fns -> merchant ID
- fix step for create auth token and add separate step for create session token
- Launch merchants faster and make it easier to integrate with Forage
- Improve Forage product quality + perception with consistent naming, clearer instructions and better comments
Stack is released together into next major version release
Migration guide can be [found here](https://github.com/teamforage/forage-ios-sdk/pull/60#migration-guide:~:text=Migration%20guide%20(v3%20%2D%3E%20v4))
> [FX-402] Refactor ForageSDK.Config params (merchantAccount, bearerToken)

- Sources/ForageSDK/Component/ForagePANTextField/ForagePANTextField.swift
- Sources/ForageSDK/Component/ForagePINTextField/ForagePINTextField.swift
- Sources/ForageSDK/ForageSDK.swift
- Sources/ForageSDK/Foundation/ForageSDK+ForageServices.swift
- Sources/ForageSDK/Foundation/Network/Collector.swift
- Sources/ForageSDK/Foundation/Network/LDManager.swift
- Sources/ForageSDK/Foundation/Network/LiveForageService.swift
- Sources/ForageSDK/Foundation/Network/Provider.swift
- Sources/ForageSDK/Foundation/Telemetry/ForageLogger.swift
- Add log statements with helpful attributes (context), prefixes
- Logs all HTTP requests and responses
- Logs all errors with level "error"
Learn more: https://docs.google.com/document/d/1NYe6JtnBJAVrtjIKREdwoBt3lqh18vfXqzj9EaodXhI/edit#bookmark=id.2rdd25jqml4p
DD logs https://app.datadoghq.com/logs?query=service%3Aios-sdk%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1690904666204&to_ts=1690904713184&live=false
This PR Stack (FX-317) can be considered a patch-level change.
This PR is based off of #54
> [FX-317] Part 2: Add log statements

- Sources/ForageSDK/ForageSDK.swift
- Sources/ForageSDK/Foundation/ForageSDK+ForageServices.swift
Expose the version number as a public static variable.
> [FX-445] Expose version number as public static variable

- Sources/ForageSDK/Component/ForagePANTextField/ForagePANTextField.swift
Short circuit validation logic based on special cards.
> [FX-454] Short circuit validation logic when not in production

- ForageSDK.podspec
- Package.swift
- Sources/ForageSDK/Component/ForagePINTextField/ForagePINTextField.swift
- Sources/ForageSDK/Component/ForagePINTextField/Vault/BtPINTextField.swift
Implement the focus event handler for BT based on changes they made for us.
I tested visually in the sample app
> [FX-389] iOS add support for onfocuschanged event listener for bt

- Sample/SampleForageSDK/Sections/CardNumber/CardNumberView.swift
Display the PAN state on the sample app so the qa-tests can reference it.
> [FX-513] Display PAN state on screen

- Sample/SampleForageSDK/Sections/CapturePayment/CapturePaymentView.swift
- Sources/ForageSDK/Foundation/Network/LiveForageService.swift
- Sources/ForageSDK/Foundation/Network/Model/ForageErrorModel.swift
- Sources/ForageSDK/Foundation/Network/Model/MessageResponseModel.swift
Reverts teamforage/forage-ios-sdk#94
Will attempt to add error details [as described in strategy B here](https://www.notion.so/joinforage/Details-in-Error-Object-Discussion-c1948a15620f477ea9e426e60ad701ca)
> Revert "[FX-529] Add support for error details"

- Sources/ForageSDK/Foundation/Network/LiveForageService.swift
- Increase polling timeout from 10sec -> 90sec 
- Reason in [this slack message](https://joinforage.slack.com/archives/C056QGRF6S3/p1692031634566089?thread_ts=1692031426.000509&cid=C056QGRF6S3)
- Branch name is misleading, looks like 90sec is the actual timeout
- [Slack thread](https://joinforage.slack.com/archives/C056QGRF6S3/p1692032168600679?thread_ts=1692031426.000509&cid=C056QGRF6S3) 
> [FX-450] Increase polling timeout to 90sec

- README.md
- Sample/SampleForageSDK/Sections/CapturePayment/CapturePaymentView.swift
- Sample/SampleForageSDK/Sections/RequestBalance/RequestBalanceView.swift
- Sources/ForageSDK/Component/ForagePINTextField/ForagePINTextField.swift
This field has no use anymore and can be removed. I am going to get in touch with GoPuff to ensure that they don't use the field.
> [FX-388] Remove pinType field

- Sources/ForageSDK/Component/ForagePINTextField/ForagePINTextField.swift
- Sources/ForageSDK/Component/ForagePINTextField/Protocol/VaultWrapper.swift
- Sources/ForageSDK/Component/ForagePINTextField/Vault/BtPINTextField.swift
- Sources/ForageSDK/Component/ForagePINTextField/Vault/VgsPINTextField.swift
- Sources/ForageSDK/Foundation/Protocol/ForageElement.swift
- Tests/ForageSDKTests/ForagePINTextFieldTests.swift
Partially revert #92
https://linear.app/joinforage/issue/FX-574/ios-fix-height-and-width-attributes
> [FX-574] Remove height and width attributes

- ForageSDK.podspec
- Package.swift
- Upgrade `BasisTheoryElements` from 2.8.0 -> 4.0.0
- More ctx [in Linear](https://linear.app/joinforage/issue/FX-638/upgrade-bt-ios-to-version-400-to-fix-bug)
Can be released as-is along with the parent PR #115 !
> Upgrade Basis Theory to 4.0.0

- Sample/SampleForageSDK/Foundation/Network/Provider.swift
- Sources/ForageSDK/Component/ForagePINTextField/ForagePINTextField.swift
- Sources/ForageSDK/ForageSDK.swift
- Sources/ForageSDK/Foundation/Network/ForageAPI.swift
- Sources/ForageSDK/Foundation/Network/LDManager.swift
- Sources/ForageSDK/Foundation/Network/LiveForageService.swift
- Sources/ForageSDK/Foundation/Network/Protocol/Polling.swift
- Sources/ForageSDK/Foundation/Network/Provider.swift
- Tests/ForageSDKTests/ForageServiceTests.swift
- Tests/ForageSDKTests/LDManagerTests.swift
Add the polling feature flag to include new polling intervals.
- ✅ Not a front-end change
> [FX-608] Add polling feature flag

- README.md
- new photos
- fix outdated info
- remove extraneous info
> [FX 663] Refresh README

- README.md
FNS now prohibits offering a balance check if your site or app has a guest checkout flow. This PR adds that callout to the method step. 
We should over-communicate this to customers to prevent future blockages during testing. 
-  ❌ I've added unit tests for this change. 
- ✅ | ❌ The reviewer should manually test the changes in this PR. 
I didn't create Unit tests because this is just a Readme change. For a Readme change, you can pull the branch and preview the markdown in your code editor before merging. 
N/A
N/A
> [TW-339] Update iOS readme with callout

- ForageSDK.podspec
- Sources/ForageSDK/ForageSDK.swift
- Bump to v4.1.3
- Fix README shown on [the public cocoapods registry](https://cocoapods.org/pods/ForageSDK)
Can 
> Release version 4.1.3

- .github/workflows/qa-tests.yaml
- Sample/fastlane/Fastfile
- fixed a typo
- removes leftover print statement
- testing concurrent builds
> Fix typo in Github action

- .github/workflows/qa-tests.yaml
Add ability to manually trigger the QA tests workflow
Improve dev experience
> Support workflow dispatch

- Sources/ForageSDK/Component/ForagePANTextField/ForagePANTextField.swift
- Heighten PAN height constraint to be >= 37
- Prevent layout constraint violations and reduce warning messages outputted from the Forage SDK
> [FX-845] Loosen PAN height constraint

- Sample/SampleForageSDK.xcodeproj/project.pbxproj
- Sample/SampleForageSDK/Base.lproj/Main.storyboard
- Sample/SampleForageSDK/Foundation/Base/BaseSampleView.swift
- Sample/SampleForageSDK/Sections/CapturePayment/CapturePaymentView.swift
- Sample/SampleForageSDK/Sections/CardNumber/CardNumberView.swift
- Sample/SampleForageSDK/Sections/CardNumber/CardNumberViewController.swift
- Sample/SampleForageSDK/Sections/CreatePayment/CreatePaymentView.swift
- Sample/SampleForageSDK/Sections/PaymentSheet/PaymentSheetView.swift
- Sample/SampleForageSDK/Sections/PaymentSheet/PaymentSheetViewController.swift
- Sample/SampleForageSDK/Sections/RequestBalance/RequestBalanceView.swift
- Sample/SampleForageSDK/ViewController.swift
- Sources/ForageSDK/Component/ForagePANTextField/ForagePANTextField.swift
- Sources/ForageSDK/Component/ForagePANTextField/MaskedUITextField.swift
- Sources/ForageSDK/Foundation/Protocol/ForagePANElement.swift
- Tests/ForageSDKTests/ForagePANTextFieldTests.swift
- Tests/ForageSDKTests/MaskedUITextFieldTests.swift
- Sample app enhancements (styling for PAN + balance PIN element, improved copy, reduce duplication, etc.)
- Adds new sample app view for the new `ForagePaymentSheet`:
Base PR for #132
> Add sample app view for new ForagePaymentSheet

- Sample/SampleForageSDK/Foundation/Base/BaseSampleView.swift
- Sample/SampleForageSDK/Sections/CardNumber/CardNumberView.swift
- Sample/SampleForageSDK/Sections/RequestBalance/RequestBalanceView.swift
- Sources/ForageSDK/Component/ForagePINTextField/ForagePINTextField.swift
- Sources/ForageSDK/Foundation/ForageSDK+ForageServices.swift
- Sources/ForageSDK/Foundation/Network/Collector.swift
- Sources/ForageSDK/Foundation/Network/LDManager.swift
- Sources/ForageSDK/Foundation/Network/LiveForageService.swift
- Sources/ForageSDK/Foundation/Network/Protocol/ForageService.swift
- Sources/ForageSDK/Foundation/Telemetry/ResponseMonitor.swift
- Tests/ForageSDKTests/ForagePublicSubmitMethodTests.swift
- Tests/ForageSDKTests/ForageServiceTests.swift
- Tests/ForageSDKTests/LDManagerTests.swift
- Tests/ForageSDKTests/Mock/MockLogger.swift
- Tests/ForageSDKTests/ResponseMonitorTests.swift
- https://linear.app/joinforage/issue/FX-799/ios-implement-the-collectpin-function
~I plan on adding unit tests if possible and will add to the sample app.~
Can be released as-is, but should be followed by this sample app diff as well #141 AND #143
> [FX-799] Expose deferPaymentCapture

- ForageSDK.podspec
- Package.swift
- Sample/SampleForageSDK/Sections/CapturePayment/CapturePaymentView.swift
- Sources/ForageSDK/Foundation/Network/LDManager.swift
- Bump BasisTheory from 4.0.0 to 4.0.2
- includes the following changes: https://github.com/Basis-Theory/basistheory-ios/compare/4.0.0...4.0.2
Gracefully handle empty proxy responses
- ✅ Tested locally against Basis Theory after the version bump
> [FX-911] Bump Basis Theory to 4.0.2

- README.md
Adding documentation for new method. 
Docs will help anybody reading the Readme to know how the function works. 
- ✅ | Not a front-end change
- ✅ | Previewed Markdown in VSCode 
- I'll close the PR if it breaks things, but this just edited the README.md
> [FX-882] Document deferPaymentCapture in README.md

- README.md
> Update  README snippet formatting

- ForageSDK.podspec
- README.md
- Sources/ForageSDK/ForageSDK.swift
**Includes the following improvements:**
- #147 
- #145
> Release v4.4.0

- ForageSDK.podspec
- README.md
- Sources/ForageSDK/ForageSDK.swift
> Bump to v4.4.1

- README.md
I added a link to the guide to deferred payment capture under the relevant function. 
This could help any developers who might be interested in more comprehensive step-by-step instructions. 
- ✅ | Not a front-end change
- ✅ | iOS QA Tests passed locally
- ✅ | I tested my changes in VSCode 
I will open a PR to rollback if things break!
> Add link to Forage guide to deferring payment capture

- Sources/ForageSDK/Foundation/Network/LiveForageService.swift
> Always fail parsing on deferred capture if we reach the parsing stage

- ForageSDK.podspec
- Sources/ForageSDK/ForageSDK.swift
> Release v4.4.7

- ForageSDK.podspec
- Sources/ForageSDK/Component/ForagePINTextField/Vault/RosettaPINTextField.swift
- Sources/ForageSDK/ForageSDK.swift
- Sources/ForageSDK/Foundation/ForageSDK+ForageServices.swift
- Sources/ForageSDK/Foundation/Network/Collector.swift
- Sources/ForageSDK/Foundation/Telemetry/ForageLogger.swift
- Tests/ForageSDKTests/CollectorTests.swift
- Tests/ForageSDKTests/ForagePINTextFieldTests.swift
- Tests/ForageSDKTests/ForageSDKTests.swift
- Tests/ForageSDKTests/Mock/MockLogger.swift
- Tests/ForageSDKTests/Mock/URLSessionDataTaskMock.swift
> Release v4.4.8

- Sources/ForageSDK/Component/ForagePANTextField/ForagePANValidations.swift
- Sources/ForageSDK/Component/ForagePANTextField/MaskedUITextField.swift
- Tests/ForageSDKTests/ForagePANTextFieldTests.swift
- Tests/ForageSDKTests/ForagePANValidationsTests.swift
- Tests/ForageSDKTests/ForagePINTextFieldTests.swift
- Tests/ForageSDKTests/MaskedUITextFieldTests.swift
- Allow 16 & 19 digit ME cards
Can be released as-is, ASAP - will release with #190
> [FX-1873] Relax PAN validation for ME

- ForageSDK.podspec
- Sources/ForageSDK/ForageSDK.swift
- includes #193 and #190 
- Fix PAN validation edge case for ME cards
- ⚡ Reduce SDK latency and reduce Package binary size!
Release ASAP
> Release v4.4.10

- Sample/SampleForageSDK/Sections/CardNumber/CardNumberView.swift
- Sources/ForageSDK/Utilities/CardTextRecognition.swift
- Tests/ForageSDKTests/ForagePANTextFieldTests.swift
merge Rob's work into the hackathon prototype
> Add recognizeCardText function to main SDK utilities

- .github/workflows/Coverage.yaml
- Sample/SampleForageSDK/Sections/CardNumber/CardNumberView.swift
- Sources/ForageSDK/Component/Common/PoweredByForageImage.swift
- Sources/ForageSDK/Foundation/Network/Model/PaymentMethodModel.swift
- Tests/ForageSDKTests/Mock/ForageMocks.swift
- decode fingerprint_v2
- bump up the size of the powered by forage image
> add fingerprint v2
